export const BANNED_PHRASES = [
  "% of your life",
  "productivity score",
  "time you focused",
  "you didn't use",
  "addiction",
  "ADHD",
  "cure",
  "detox",
  "wellbeing diagnosis",
] as const;

export const COPY = {
  egg: {
    headline: "Nothing is tracked yet.",
    sub: "The first honest day starts tomorrow.",
  },
  onboardingWeb: {
    headline: "How the numbers are made",
    body: "Timeframe replays what the writers recorded — the app on the phone, and your browser once you import its export. It never asks you to start a timer, and it never guesses what it didn't measure.",
    disclosure: "The phone app is the writer. This page is the mirror.",
    primaryButton: "Save pins",
  },
  banners: {
    phone: (day: string) => `Phone tracker off since ${day}`,
    computer: (day: string) => `Computer tracker off since ${day}`,
    turnOn: "Turn on",
    reEnable: "Re-enable",
  },
  badges: {
    lightDay: "light day — not comparable",
    unclassified: (percent: number) => `${percent}% unclassified`,
  },
  prompts: {
    pinApps: "Pin your apps",
    reviewUnclassified: "Review unclassified",
    pinChess: "Pin chess to work or killers.",
    subLine: "Pre-checked defaults — edit any time in the first week",
    chessCaption: "Chess counts as games — pin it to work or killers if that's wrong.",
  },
  metricLabels: {
    focusSetTime: "Focus-set time",
    sink: "Sink",
    deepBlocks: "Blocks ≥15 min",
    longest: "longest",
    shareOfTrackedTime: "Share of tracked time",
    pctTrackedTime: "% of tracked time",
    zeroDeepBlocks: (longest: number) => `0 blocks ≥15 min · longest ${longest} min`,
    topSinks: "Top 5 sinks by hours",
    hoursBySource: "Hours by source",
    whenTrackedTime: "When tracked time happened",
  },
  empty: {
    noTrackedTimeYet: "No tracked time yet",
    noKillerTracked: "No killer-set time tracked",
    noBlocksYet: "no blocks yet",
    weekEmpty: "No tracked time in this range",
    weekEmptySub: "The card never renders without a label and data.",
  },
  errors: {
    ledgerUnreadable: "The ledger couldn't be read",
    nothingFabricated: "Nothing was fabricated. Try reading it again.",
    tryAgain: "Try again",
    numberUncomputable: "This number couldn't be computed",
    invalidExport: "That file isn't a Timeframe export",
    websiteUnreachable: "Couldn't reach the website — try again",
    paymentNeedsConnection: "Payment needs a connection",
    pinSaveFailed: "Couldn't save pin — tap to retry",
    blockStartFailed: "Block couldn't start — try again",
  },
  block: {
    start: "Start block",
    end: "End block",
    newBlock: "New block",
    cancelled: "Cancelled",
    completed: "Completed",
    targetReached: (mins: number) => `target reached · ${mins} min`,
    focusLive: "focus-set time · live",
    samplingUnavailable: "sampling unavailable — tracker off",
    endOfReplay: "End of replay",
    deathLine: (killer: string, sec: number) => `Broken — ${killer} was open ${sec}s`,
    deathPrivate: "Broken — private app",
    deathFloorLabel: "Death floor — when a killer ends a block",
  },
  footer: {
    format: (d: number, dp: number, dc: number, u: number, h: string) =>
      `Tracked ${d} days · phone up ${dp}/${d} · computer up ${dc}/${d} · unclassified ${u}% · double-counted ${h}h`,
    preflight: "Private apps stay off this card.",
    watermark: "Timeframe",
  },
  pricing: {
    headline: "The ledger is free forever. You pay for the creature and the card.",
    freeSub: "No card. The three daily numbers, the heatmap, the \"tracker off\" banner — free, for good.",
    paidSub: "Everything in Free, plus: a creature that grows with your focus-set time, streaks, the killer that broke the block by name, and the clean share card.",
    proHeader: "Pro — ₹499/month · ₹2,999/year · or ₹599 once (classic skin, forever)",
    gst: "All prices in ₹ (INR), inclusive of 18% GST.",
    restorePrompt: "Restore purchase — paste the order ID from your payment confirmation (starts with \"pay_\" or \"sub_\").",
  },
  marketing: {
    hero: "The phone and the browser already know. Timeframe just tells you the truth.",
    ctaSeeLedger: "See the honest ledger",
    ctaStartPro: "Start Pro",
    footnote: "Honest approximations of screen occupancy — never attention, never intent.",
  },
  demoPill: "Demo data — these numbers are from a sample week.",
};
